# Generated by Django 4.0.6 on 2022-07-14 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('slack_messages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLink',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('is_removed', models.BooleanField(default=False)),
                ('id', model_utils.fields.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ts', models.CharField(db_index=True, max_length=255)),
                ('permalink', models.URLField()),
                ('priority', models.PositiveSmallIntegerField(choices=[(0, 'Highest'), (1, 'High'), (2, 'Medium'), (3, 'Low'), (4, 'Lowest')], db_index=True, default=2)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages_by_channel', to='slack_messages.slackchannel')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_messages_by_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
                'abstract': False,
            },
        ),
    ]
